### ISSUE TITLE
Error parsing Application log data

### ISSUE THREAD

**Issue by commandeurbrin** [the-hideout/TarkovMonitor#44] opened 2023-12-29 18:45 UTC
Hi, 

I've installed and launched the exe and It did retrieve data from tarkov dev but I only get Error parsing Application log data afterwards. 

#
Error parsing Application log data 2023-12-29 19:03:20.711 +01:00|0.14.0.0.28375|Info|application|MatchingCompleted:66.88 real:77.66 diff:10.78 2023-12-29 19:03:20.803 +01:00|0.14.0.0.28375|Debug|application|TRACE-GamePrepare 2 2023-12-29 19:03:20.803 +01:00|0.14.0.0.28375|Info|application|GamePrepared:66.96 real:77.75 diff:10.79 2023-12-29 19:03:20.803 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 0 2023-12-29 19:03:20.803 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 2 2023-12-29 19:03:20.911 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 3 2023-12-29 19:03:20.911 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate profileStatus: 'Profileid: 60008306b4df3523a949cf7b, Status: Busy, RaidMode: Online, Ip: 37.19.203.86, Port: 17003, Location: Shoreline, Sid: 37.19.203.86-17003_PID_29.12.23_18.01.18, GameMode: deathmatch, shortId: PQXKR6' 2023-12-29 19:03:20.911 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 4 2023-12-29 19:03:20.911 +01:00|0.14.0.0.28375|Info|application|GameCreated:67.08(0.12) real:77.86(0.11) diff:10.77 2023-12-29 19:03:20.911 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 5 : Input string was not in a correct format. at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 141

#
Error parsing Application log data 2023-12-29 19:02:53.014 +01:00|0.14.0.0.28375|Info|application|LocationLoaded:39.13 real:49.96 diff:10.82 : Input string was not in a correct format. at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 141

# 
Error parsing Application log data 2023-12-29 18:34:52.545 +01:00|0.14.0.0.28375|Info|application|MatchingCompleted:587.5 real:593.21 diff:5.71 2023-12-29 18:34:52.684 +01:00|0.14.0.0.28375|Debug|application|TRACE-GamePrepare 2 2023-12-29 18:34:52.684 +01:00|0.14.0.0.28375|Info|application|GamePrepared:587.63 real:593.35 diff:5.71 2023-12-29 18:34:52.684 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 0 2023-12-29 18:34:52.684 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 2 2023-12-29 18:34:52.795 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 3 2023-12-29 18:34:52.795 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate profileStatus: 'Profileid: 60008306b4df3523a949cf7a, Status: Busy, RaidMode: Online, Ip: 84.17.62.207, Port: 17002, Location: Sandbox, Sid: 84.17.62.207-17002_PID_29.12.23_17.13.49, GameMode: deathmatch, shortId: PQYC4K' 2023-12-29 18:34:52.812 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 4 2023-12-29 18:34:52.812 +01:00|0.14.0.0.28375|Info|application|GameCreated:587.75(0.11) real:593.49(0.14) diff:5.73 2023-12-29 18:34:52.826 +01:00|0.14.0.0.28375|Debug|application|TRACE-NetworkGameCreate 5 : Input string was not in a correct format. at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 141
#

What can I do ? 

Thanks for your help !

**Comment by Razzmatazzz** [comment] 2024-01-16 21:04
This is very strange; when I paste those log entries into the custom parser, it reads just fine. Does this happen constantly or just occasionally?

**Comment by Razzmatazzz** [comment] 2024-01-16 21:05
But closing this as a duplicate of #21

**Closed by Razzmatazzz** 2024-01-16 21:05 UTC
