### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by kwaio** [the-hideout/TarkovMonitor#85] opened 2024-08-14 17:49 UTC
Hi.
When coming back from Windows sleep, tarkov monitor seems to go in a loop where it continuously queries... tarkov.dev I guess ? and memory keeps growing until OOM
![image](https://github.com/user-attachments/assets/8054d66d-7ce4-4d61-aeb8-24296ef210c6)
I can't see any log I could pass to help troubleshooting ?

**Comment by Razzmatazzz** [comment] 2024-08-15 18:14
Duplicate of #82 

This is related to the remote control feature being unable to establish a websocket connection. It seems to be related to Windows not thinking it has a fully working internet connection after waking from sleep.

**Closed by Razzmatazzz** 2024-08-15 18:14 UTC
