### ISSUE TITLE
Parsing error is coming up several times in activity view.

### ISSUE THREAD

**Issue by Dontzi** [the-hideout/TarkovMonitor#34] opened 2023-08-21 19:12 UTC
Error parsing log data: Input string was not in a correct format. at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in D:\a\TarkovMonitor\TarkovMonitor\TarkovMonitor\GameWatcher.cs:line 141

Im guessing this also relates to that remote control does not work and the loading in voice line is not working.

**Comment by Razzmatazzz** [comment] 2023-08-22 11:39
Can you post your application.log and notifications.log from a game session when  you received these errors? They're in your EFT/Logs folder, in subfolders named according to the time the game was started.

**Comment by Dontzi** [comment] 2023-08-22 13:25
[2023.08.21_17-33-15_0.13.5.0.25837 notifications.log](https://github.com/the-hideout/TarkovMonitor/files/12409103/2023.08.21_17-33-15_0.13.5.0.25837.notifications.log)
[2023.08.21_17-33-15_0.13.5.0.25837 application.log](https://github.com/the-hideout/TarkovMonitor/files/12409105/2023.08.21_17-33-15_0.13.5.0.25837.application.log)

**Comment by Razzmatazzz** [comment] 2023-11-28 20:55
Duplicate of #21

**Closed by Razzmatazzz** 2023-11-28 20:55 UTC
